#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

GPU_PHYSICAL_INDEX="${1:-${GPU_PHYSICAL_INDEX:-2}}"
PY_ENV_PREFIX="${PY_ENV_PREFIX:-/home/op/miniconda3/bin}"
CELERY_BIN="${CELERY_BIN:-$PY_ENV_PREFIX/celery}"

BRITISH_WOMAN_REF="/home/op/Libro-Gregoria-Variacion/audio/britishWoman_clean.wav"
DEFAULT_FALLBACK="$PWD/voices/default.wav"

export VOICE_DIR="${VOICE_DIR:-$PWD/voices}"
export DEFAULT_VOICE="${DEFAULT_VOICE:-}"
if [[ -z "$DEFAULT_VOICE" ]]; then
  if [[ -f "$BRITISH_WOMAN_REF" ]]; then
    export DEFAULT_VOICE="$BRITISH_WOMAN_REF"
  else
    export DEFAULT_VOICE="$DEFAULT_FALLBACK"
  fi
fi

# English base + Spanish Lucía profiles.
export SPANISH_ENABLED="${SPANISH_ENABLED:-1}"
export BASE_MODEL_REPO="${BASE_MODEL_REPO:-ResembleAI/chatterbox-turbo}"
export BASE_MODEL_REVISION="${BASE_MODEL_REVISION:-main}"
export BASE_MODEL_DIR="${BASE_MODEL_DIR:-}"
export SPANISH_MODEL_REPO="${SPANISH_MODEL_REPO:-groxaxo/chaturbo-espanol}"
export SPANISH_MODEL_REVISION="${SPANISH_MODEL_REVISION:-main}"
export SPANISH_MODEL_DIR="${SPANISH_MODEL_DIR:-}"
export DEFAULT_SPANISH_PROFILE="${DEFAULT_SPANISH_PROFILE:-lucia-ar}"
export SPANISH_PROFILE_CACHE_SIZE="${SPANISH_PROFILE_CACHE_SIZE:-1}"
export PRELOAD_PROFILES="${PRELOAD_PROFILES:-}"
export STRICT_SPANISH_TAGS="${STRICT_SPANISH_TAGS:-1}"
export VERIFY_MODEL_PROVENANCE="${VERIFY_MODEL_PROVENANCE:-1}"
export ENABLE_WATERMARK="${ENABLE_WATERMARK:-0}"

# Exact-output Chatterbox Turbo hot-path optimizations.
export TURBO_PERFORMANCE_RUNTIME="${TURBO_PERFORMANCE_RUNTIME:-1}"
export TURBO_EXPECTED_CHATTERBOX_VERSIONS="${TURBO_EXPECTED_CHATTERBOX_VERSIONS:-0.1.6,0.1.7}"
export TURBO_FAIL_ON_INCOMPATIBLE_PACKAGE="${TURBO_FAIL_ON_INCOMPATIBLE_PACKAGE:-0}"
export TURBO_CACHE_ENCODED_CONDITIONING="${TURBO_CACHE_ENCODED_CONDITIONING:-1}"
export TURBO_PREALLOCATE_TOKEN_IDS="${TURBO_PREALLOCATE_TOKEN_IDS:-1}"
export TURBO_CACHE_SILENCE_TENSOR="${TURBO_CACHE_SILENCE_TENSOR:-1}"
export TURBO_DISABLE_PROGRESS="${TURBO_DISABLE_PROGRESS:-1}"
export TURBO_STRICT_LOGIT_CHECKS="${TURBO_STRICT_LOGIT_CHECKS:-1}"
export TURBO_REWRITE_PACKAGE_GENERATE="${TURBO_REWRITE_PACKAGE_GENERATE:-1}"

# Optional acceleration. See ACCELERATION.md before changing the default.
export TURBO_ACCELERATOR="${TURBO_ACCELERATOR:-torch}"
export TURBO_ACCELERATOR_FAIL_CLOSED="${TURBO_ACCELERATOR_FAIL_CLOSED:-0}"
export TURBO_TENSORRT_BACKEND="${TURBO_TENSORRT_BACKEND:-torch_tensorrt}"
export TURBO_TENSORRT_DYNAMIC="${TURBO_TENSORRT_DYNAMIC:-0}"
export TURBO_TENSORRT_FULLGRAPH="${TURBO_TENSORRT_FULLGRAPH:-0}"
export TURBO_TENSORRT_REQUIRE_FP32="${TURBO_TENSORRT_REQUIRE_FP32:-1}"
export TURBO_VLLM_BASE_URL="${TURBO_VLLM_BASE_URL:-http://127.0.0.1:8000}"
export TURBO_VLLM_HEALTH_PATH="${TURBO_VLLM_HEALTH_PATH:-/health}"
export TURBO_VLLM_SPEECH_PATH="${TURBO_VLLM_SPEECH_PATH:-/v1/audio/speech}"
export TURBO_VLLM_MODEL="${TURBO_VLLM_MODEL:-tts-1}"
export TURBO_VLLM_PROFILES="${TURBO_VLLM_PROFILES:-english}"
export TURBO_VLLM_VOICE_MAP="${TURBO_VLLM_VOICE_MAP:-english=alloy}"
export TURBO_VLLM_TIMEOUT_SECONDS="${TURBO_VLLM_TIMEOUT_SECONDS:-180}"
export TURBO_VLLM_EXCLUSIVE="${TURBO_VLLM_EXCLUSIVE:-0}"

export ENABLE_CELERY=0
export CHATTERBOX_WORKER_BOOTSTRAP=1
export DEVICE="${DEVICE:-cuda}"
export REQUIRE_CUDA="${REQUIRE_CUDA:-1}"
export EXPECTED_GPU_NAME="${EXPECTED_GPU_NAME:-RTX 3090}"
export CELERY_BROKER_URL="${CELERY_BROKER_URL:-redis://127.0.0.1:6379/14}"
export CELERY_RESULT_BACKEND="${CELERY_RESULT_BACKEND:-$CELERY_BROKER_URL}"
export CELERY_QUEUE="${CELERY_QUEUE:-chatterbox_tts}"
export WORKER_LAZY_LOAD_MODEL="${WORKER_LAZY_LOAD_MODEL:-0}"
export WORKER_MODEL_IDLE_UNLOAD_SECONDS="${WORKER_MODEL_IDLE_UNLOAD_SECONDS:-${MODEL_IDLE_UNLOAD_SECONDS:-0}}"
export WORKER_STARTUP_WARMUP="${WORKER_STARTUP_WARMUP:-1}"
export LAZY_LOAD_MODEL="$WORKER_LAZY_LOAD_MODEL"
export MODEL_IDLE_UNLOAD_SECONDS="$WORKER_MODEL_IDLE_UNLOAD_SECONDS"
export MODEL_IDLE_CHECK_INTERVAL_SECONDS="${MODEL_IDLE_CHECK_INTERVAL_SECONDS:-30}"
export MIN_FREE_VRAM_MB="${MIN_FREE_VRAM_MB:-3500}"
export MODEL_LOAD_WAIT_TIMEOUT_SECONDS="${MODEL_LOAD_WAIT_TIMEOUT_SECONDS:-60}"
export AUTO_CHUNK_ENABLED="${AUTO_CHUNK_ENABLED:-1}"
export AUTO_CHUNK_TARGET_CHARS="${AUTO_CHUNK_TARGET_CHARS:-520}"
export AUTO_CHUNK_HARD_LIMIT="${AUTO_CHUNK_HARD_LIMIT:-580}"
export MIN_CHUNK_CHARS="${MIN_CHUNK_CHARS:-0}"
export CHUNK_PAUSE_MS="${CHUNK_PAUSE_MS:-140}"
export DEFAULT_RESPONSE_FORMAT="${DEFAULT_RESPONSE_FORMAT:-mp3}"
export MAX_INPUT_CHARS="${MAX_INPUT_CHARS:-12000}"
export MAX_TEXT_CHARS="${MAX_TEXT_CHARS:-520}"
export MAX_UPLOAD_MB="${MAX_UPLOAD_MB:-25}"
export VOICE_CACHE_SIZE="${VOICE_CACHE_SIZE:-8}"
export STARTUP_WARMUP="$WORKER_STARTUP_WARMUP"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

mkdir -p "$VOICE_DIR"

GPU_INFO="$(nvidia-smi --query-gpu=index,uuid,name --format=csv,noheader | awk -F', ' -v idx="$GPU_PHYSICAL_INDEX" '$1 == idx {print $2 "|" $3; exit}')"
if [[ -z "$GPU_INFO" ]]; then
  echo "ERROR: Could not resolve physical GPU index $GPU_PHYSICAL_INDEX via nvidia-smi." >&2
  exit 1
fi

GPU_UUID="${GPU_INFO%%|*}"
GPU_NAME="${GPU_INFO#*|}"
if [[ -n "$EXPECTED_GPU_NAME" && "$GPU_NAME" != *"$EXPECTED_GPU_NAME"* ]]; then
  echo "ERROR: Physical GPU index $GPU_PHYSICAL_INDEX resolved to '$GPU_NAME', expected '$EXPECTED_GPU_NAME'." >&2
  exit 1
fi

export CUDA_VISIBLE_DEVICES="$GPU_UUID"

exec "$CELERY_BIN" -A multilingual_celery_worker.celery_app worker \
  --loglevel="${CELERY_LOGLEVEL:-INFO}" \
  --pool=solo \
  --concurrency=1 \
  --queues="$CELERY_QUEUE" \
  --hostname="chatterbox-gpu${GPU_PHYSICAL_INDEX}@%h"
